{
  "youtube": {
    "api_key": "YOUR_YOUTUBE_API_KEY",
    "client_id": "YOUR_YOUTUBE_CLIENT_ID",
    "client_secret": "YOUR_YOUTUBE_CLIENT_SECRET"
  },
  "twitter": {
    "api_key": "YOUR_TWITTER_API_KEY",
    "api_secret": "YOUR_TWITTER_API_SECRET",
    "access_token": "YOUR_TWITTER_ACCESS_TOKEN",
    "access_token_secret": "YOUR_TWITTER_ACCESS_TOKEN_SECRET"
  }
}